/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js}"],
  theme: {
    extend: {},
    colors: {
      transparent: "transparent",
      current: "currentColor",
      salmonPink: "#f49097",
      mauve: "#DFB2F4",
      corn: "#f5e960",
      ghostWhite: "#f2f5ff",
      turquoise: "#55d6c2",
      cryola: "#963484",
      trueBlue: "#3066be",
      skyBlue: "#60afff",
      carpi: "#28c2ff",
      electricBlue: "#2af5ff",
      white: "#ffffff",
      purple: "#3f3cbb",
      midnight: "#121063",
      metal: "#565584",
      tahiti: "#3ab7bf",
      silver: "#ecebff",
      "bubble-gum": "#ff77e9",
      bermuda: "#78dcca",
      black: "#000",
      mildGray: "#6A67674D",
    },
  },
  plugins: [],
};
